# 作业-Numpy

运用Numpy1维、2维数组相关的创建、切片、运算等方法解决以下问题：

## 1. 一维数组
- 创建一个1维数组，命名为data01，包含100，99，...，1，间隔为1
- 对其进行从小到大排序
- 将数组data01变形成4行25列的2维数组
- 计算总和

In [1]:
import numpy as np
data01 = np.arange(100, 0, -1)
data01.sort()
data02 = data01.reshape((4, 25))
sum_data = data01.sum()
print("一维数组为：\n", data01)
print("变形后的二维数组为：\n", data02)
print("总和为：", sum_data)


一维数组为：
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
变形后的二维数组为：
 [[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25]
 [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
   44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94  95  96  97  98  99 100]]
总和为： 5050


## 2.二维数组
- 创建一个大小为3行4列的2维随机数组，数组中的元素维随机数，命名为data02
- 选取数组data02后3列，也就是第2列到第4列元素
- 求数组data02的元素中的最大值、最小值和总和。
- 求数组data02的元素中的每一列求最大值、最小值和总和。
- 将data02变形成1维数组。
- 将data02变成4行3列的2维数组



In [2]:
import numpy as np
data02 = np.random.rand(3, 4)
data03 = data02[:, 1:]
max_data = np.max(data02)
min_data = np.min(data02)
sum_data = np.sum(data02)
max_data_col = np.max(data02, axis=0)
min_data_col = np.min(data02, axis=0)
sum_data_col = np.sum(data02, axis=0)
data04 = data02.flatten()
data05 = data02.reshape((4, 3))
print("二维随机数组data02为：\n", data02)
print("选取data02的后3列为：\n", data03)
print("data02的最大值为：", max_data)
print("data02的最小值为：", min_data)
print("data02的总和为：", sum_data)
print("data02每一列的最大值为：", max_data_col)
print("data02每一列的最小值为：", min_data_col)
print("data02每一列的总和为：", sum_data_col)
print("data02变形后的4行3列的2维数组为：\n", data05)

二维随机数组data02为：
 [[0.24490918 0.23138777 0.98924298 0.03153811]
 [0.27407632 0.02302064 0.27067469 0.36724631]
 [0.73858161 0.09076197 0.24816232 0.43011949]]
选取data02的后3列为：
 [[0.23138777 0.98924298 0.03153811]
 [0.02302064 0.27067469 0.36724631]
 [0.09076197 0.24816232 0.43011949]]
data02的最大值为： 0.9892429842337694
data02的最小值为： 0.023020636276608775
data02的总和为： 3.9397213991776927
data02每一列的最大值为： [0.73858161 0.23138777 0.98924298 0.43011949]
data02每一列的最小值为： [0.24490918 0.02302064 0.24816232 0.03153811]
data02每一列的总和为： [1.25756712 0.34517038 1.50807999 0.82890391]
data02变形后的4行3列的2维数组为：
 [[0.24490918 0.23138777 0.98924298]
 [0.03153811 0.27407632 0.02302064]
 [0.27067469 0.36724631 0.73858161]
 [0.09076197 0.24816232 0.43011949]]


## 3.最小最大标准化

最小最大标准化（Min-Max Normalization）是一种常用的数据标准化方法，用于将数据缩放到指定的范围内。
该方法通过对数据进行线性变换，使其值域被缩放到指定的范围内，通常是 [0,1] 或 [-1,1]。

该方法的公式如下：

$$
X_{norm} = (X - X_{min}) / (X_{max} - X_{min})
$$

通过最小最大标准化，可以使得不同量纲的数据在同一标度下进行比较，且可以使得数据具有可比性。
在机器学习、数据挖掘等领域中，常常需要对数据进行标准化，以提高算法的性能和效果。

应用上述方法，将序列[16, 46, 33, 90, 64, 34, 91, 33, 24, 32, 30, 91, 85, 58, 77, 35,  1,34, 51, 36]进行最小最大标准化操作，放缩到[0,1]。

In [3]:
data = [16, 46, 33, 90, 64, 34, 91, 33, 24, 32, 30, 91, 85, 58, 77, 35, 1, 34, 51, 36]
x_min = min(data)
x_max = max(data)
data_normalized = [(x-x_min)/(x_max-x_min) for x in data]
print(data_normalized)

[0.16666666666666666, 0.5, 0.35555555555555557, 0.9888888888888889, 0.7, 0.36666666666666664, 1.0, 0.35555555555555557, 0.25555555555555554, 0.34444444444444444, 0.32222222222222224, 1.0, 0.9333333333333333, 0.6333333333333333, 0.8444444444444444, 0.37777777777777777, 0.0, 0.36666666666666664, 0.5555555555555556, 0.3888888888888889]


## 4. 数据集划分

在机器学习中，样本内和样本外是指数据集中的一部分样本，其中来说，样本内是指用于训练模型、调整模型参数、验证模型性能的数据；样本外是指未在训练过程中使用的数据，通常用于测试模型的性能和泛化能力。

![fix_split](image/fix_split.png)

一般将80%的原始数据集的子样本集作为样本内(In-sample, IS)，剩余20%作为样本外(Out-of-sample, OOS)。
样本总数为500个，一种简单的切割方法是直接指定前400个样本为IS，后面为OOS。

In [48]:
X = np.array([0.36707772, 0.30442107, 0.09602864, 0.72140911, 0.30727176,
       0.30332833, 0.82704939, 0.0547752 , 0.91921485, 0.54352647,
       0.45263199, 0.1654269 , 0.42571673, 0.38253443, 0.11461271,
       0.56558215, 0.78277293, 0.82637154, 0.48652071, 0.49557472])

如果给定一个X序列，那么其样本内和样本外分别是：

In [ ]:
X_IS = 
X_OOS =

简单随机划分（Simple Random Sampling）：将原始数据集随机划分为训练集和测试集两部分，通常将数据集的 70% 到 80% 作为训练集，剩余部分作为测试集。

![random_split](image/random_split.png)

当我们并不了解原始数据集是不是被刻意排列了，最好的办法是使用随机抽样，即随机抽80%为IS，剩余的20%为OOS。

In [ ]:
X_random_IS = 
X_random_OOS = 